day_3/doctoblog_ok/config/routes.rb
Rails.application.routes.draw do

  resources :appoitments
  resources :patients
  resources :doctors
    root to: 'home#index'

end

day_3/doctoblog_ok/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

day_3/doctoblog_ok/app/models/appoitment.rb
class Appoitment < ApplicationRecord
end

day_3/doctoblog_ok/app/models/doctor.rb
class Doctor < ApplicationRecord
end

day_3/doctoblog_ok/app/models/patient.rb
class Patient < ApplicationRecord
end

day_3/doctoblog_ok/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

day_3/doctoblog_ok/app/controllers/appoitments_controller.rb
class AppoitmentsController < ApplicationController
  before_action :set_appoitment, only: [:show, :edit, :update, :destroy]

  # GET /appoitments
  # GET /appoitments.json
  def index
    @appoitments = Appoitment.all
  end

  # GET /appoitments/1
  # GET /appoitments/1.json
  def show
  end

  # GET /appoitments/new
  def new
    @appoitment = Appoitment.new
  end

  # GET /appoitments/1/edit
  def edit
  end

  # POST /appoitments
  # POST /appoitments.json
  def create
    @appoitment = Appoitment.new(appoitment_params)

    respond_to do |format|
      if @appoitment.save
        format.html { redirect_to @appoitment, notice: 'Appoitment was successfully created.' }
        format.json { render :show, status: :created, location: @appoitment }
      else
        format.html { render :new }
        format.json { render json: @appoitment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appoitments/1
  # PATCH/PUT /appoitments/1.json
  def update
    respond_to do |format|
      if @appoitment.update(appoitment_params)
        format.html { redirect_to @appoitment, notice: 'Appoitment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appoitment }
      else
        format.html { render :edit }
        format.json { render json: @appoitment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appoitments/1
  # DELETE /appoitments/1.json
  def destroy
    @appoitment.destroy
    respond_to do |format|
      format.html { redirect_to appoitments_url, notice: 'Appoitment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appoitment
      @appoitment = Appoitment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appoitment_params
      params.require(:appoitment).permit(:date)
    end
end

day_3/doctoblog_ok/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:first_name, :last_name, :specialty, :postal_code)
    end
end

day_3/doctoblog_ok/app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def index
        
    end
    
end

day_3/doctoblog_ok/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name)
    end
end

day_3/doctoblog_ok/app/helpers/application_helper.rb
module ApplicationHelper
end

day_3/doctoblog_ok/app/helpers/appoitments_helper.rb
module AppoitmentsHelper
end

day_3/doctoblog_ok/app/helpers/doctors_helper.rb
module DoctorsHelper
end

day_3/doctoblog_ok/app/helpers/home_helper.rb
module HomeHelper
end

day_3/doctoblog_ok/app/helpers/patients_helper.rb
module PatientsHelper
end

day_3/doctoblog_ok/app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :doctor_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :doctor_last_name %>
  </div>

  <div class="field">
    <%= form.label :specialty %>
    <%= form.text_field :specialty, id: :doctor_specialty %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.number_field :postal_code, id: :doctor_postal_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

<br><br><%= link_to "Homepage",'/'%><br><br><br>

day_3/doctoblog_ok/app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

day_3/doctoblog_ok/app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= link_to "Docteurs",'/'%></h1>


<table>
  <thead>
    <tr>
      <th>First name |</th>
      <th>Last name |</th>
      <th>Specialty |</th>
      <th>Postal code |</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.first_name %></td>
        <td><%= doctor.last_name %></td>
        <td><%= doctor.specialty %></td>
        <td><%= doctor.postal_code %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>
<br>
<br>
<br>
<%= link_to "Homepage",'/'%>

day_3/doctoblog_ok/app/views/doctors/new.html.erb
<h1><%= link_to "Nouveau docteur",'/'%></h1>


<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

day_3/doctoblog_ok/app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @doctor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @doctor.last_name %>
</p>

<p>
  <strong>Specialty:</strong>
  <%= @doctor.specialty %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @doctor.postal_code %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

day_3/doctoblog_ok/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doctoblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>